mqtt.broker.url=tcp://127.0.0.1:1883
mqtt.topic=/ev/bms/

# amount of concurrent battery simulations
battery.count=1

# generate a data set every x seconds
data.gen.interval=3

# voltage
battery.voltage.max=48

# capacity in kwh
battery.capacity=4

# in meter per seconds
wheel.speed.max=7

# kg and meters
car.weight=100
car.width=0.96
car.height=0.43
car.tire.cr=0.014 
car.drag.cw=0.24

quarkus.http.cors.enabled=true 
quarkus.http.cors.origins=/.*/ 
quarkus.http.cors.methods=GET,PUT,POST 
quarkus.http.cors.headers=X-Custom 
quarkus.http.cors.exposed-headers=Content-Disposition 
quarkus.http.cors.access-control-max-age=24H 
quarkus.http.cors.access-control-allow-credentials=true 